### ISSUE TITLE
Red/Green is hard to see if colorblind

### ISSUE THREAD

**Issue by Summertime** [oskaerik/oskaerik.github.io#1]
An easy way to fix is to add monochrome icons, as they can be discerned regardless of color perception.

**Comment by oskaerik** [comment]
![Screenshot_20231207_194721_Samsung Internet](https://github.com/oskaerik/oskaerik.github.io/assets/23035322/79768a92-d9dc-4888-8323-b937e19dd744)

Thanks for the input! What do you think about this? 😊

**Comment by Summertime** [comment]
Looks great!
